services:
  postgres-database:
    image: postgres:16
    container_name: postgres-database
    restart: unless-stopped

    environment:
      POSTGRES_USER: ukhaan
      POSTGRES_PASSWORD: ukhaan-secret
      POSTGRES_DB: ukhaan_core

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: >
      redis-server
      --appendonly yes
      --requirepass REDIS_PASSWORD

    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: