# Generated by Django 4.2.30 on 2026-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerlog',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messengerlog',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MessengerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_facebook_id', models.CharField(max_length=120)),
                ('psid', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('message', 'message'), ('postback', 'postback'), ('delivery', 'delivery'), ('read', 'read'), ('reaction', 'reaction'), ('optin', 'optin'), ('referral', 'referral'), ('echo', 'echo'), ('unknown', 'unknown')], max_length=32)),
                ('mid', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('is_echo', models.BooleanField(default=False)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ukhaan_messenger_events',
                'indexes': [models.Index(fields=['page_facebook_id', 'psid'], name='ukhaan_mess_page_fa_605842_idx'), models.Index(fields=['mid'], name='ukhaan_mess_mid_34932e_idx')],
            },
        ),
    ]
